// <auto-generated />
using System;
using EventRegistrationApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventRegistrationApplication.Migrations
{
    [DbContext(typeof(EventRegistrationApplicationContext))]
    [Migration("20250210080148_AddSeatStatusModelAndSeedData")]
    partial class AddSeatStatusModelAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventRegistrationApplication.Domain.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Sports & Fitness",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9078),
                            DateUpdated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9112),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Music & Concert",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9123),
                            DateUpdated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9124),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Movies",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9125),
                            DateUpdated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9126),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Arts & Culture",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9128),
                            DateUpdated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9128),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Conferences & Seminars",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9130),
                            DateUpdated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9130),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Education & Workshops",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9132),
                            DateUpdated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9133),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Festivals & Celebrations",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9134),
                            DateUpdated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9135),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Trade Shows & Expos",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9137),
                            DateUpdated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9137),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Science & Innovation",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9139),
                            DateUpdated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9140),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Gaming & Esports",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9141),
                            DateUpdated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9142),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("EventRegistrationApplication.Domain.EventModel", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("EventId");

                    b.ToTable("EventModel");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            CategoryId = 1,
                            CreatedBy = "System",
                            Date = new DateTime(2025, 5, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9552),
                            DateCreated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9587),
                            DateIn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOut = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9588),
                            Description = "A thrilling Premier League clash between Liverpool and Man City.",
                            EventName = "Football Match: Liverpool vs Man City",
                            Location = "National Stadium",
                            StatusId = 1,
                            UpdatedBy = "System",
                            UserId = 1,
                            VenueId = 1
                        },
                        new
                        {
                            EventId = 2,
                            CategoryId = 2,
                            CreatedBy = "System",
                            Date = new DateTime(2025, 6, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9591),
                            DateCreated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9593),
                            DateIn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOut = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9593),
                            Description = "A captivating music concert by JJ Lin, featuring his iconic hits.",
                            EventName = "Music Event: Music Concert by JJ Lin",
                            Location = "Singapore Indoor Stadium",
                            StatusId = 1,
                            UpdatedBy = "System",
                            UserId = 1,
                            VenueId = 2
                        },
                        new
                        {
                            EventId = 3,
                            CategoryId = 3,
                            CreatedBy = "System",
                            Date = new DateTime(2025, 7, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9595),
                            DateCreated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9596),
                            DateIn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOut = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9597),
                            Description = "An epic movie showdown between Godzilla and Groot.",
                            EventName = "Movie Event: Godzilla Vs Groot",
                            Location = "Gateway Theatre (Main Theatre)",
                            StatusId = 1,
                            UpdatedBy = "System",
                            UserId = 1,
                            VenueId = 3
                        },
                        new
                        {
                            EventId = 4,
                            CategoryId = 3,
                            CreatedBy = "System",
                            Date = new DateTime(2025, 8, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9599),
                            DateCreated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9600),
                            DateIn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOut = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9600),
                            Description = "Hello Kitty enters the titan battle, joining forces with the Attack on Titan crew in an unexpected crossover!",
                            EventName = "Movie Event: Hello Kitty joined the fight of the titans! ft Attack on Titans",
                            Location = "Gateway Theatre (Main Theatre)",
                            StatusId = 1,
                            UpdatedBy = "System",
                            UserId = 1,
                            VenueId = 3
                        },
                        new
                        {
                            EventId = 5,
                            CategoryId = 1,
                            CreatedBy = "System",
                            Date = new DateTime(2025, 9, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9602),
                            DateCreated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9603),
                            DateIn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOut = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9604),
                            Description = "Arsenal will take on Newcastle in a high-stakes Carabao Cup clash at the Emirates, aiming to bounce back from a tough first-leg result.",
                            EventName = "Football Match: Arsenal vs Newcastle",
                            Location = "National Stadium",
                            StatusId = 1,
                            UpdatedBy = "System",
                            UserId = 1,
                            VenueId = 1
                        },
                        new
                        {
                            EventId = 6,
                            CategoryId = 2,
                            CreatedBy = "System",
                            Date = new DateTime(2025, 12, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9606),
                            DateCreated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9607),
                            DateIn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOut = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9608),
                            Description = "Enjoy an unforgettable night of soulful melodies and powerful performances at G.E.M's music concert!",
                            EventName = "Music Event: Music Concert by G.E.M",
                            Location = "Singapore Indoor Stadium",
                            StatusId = 1,
                            UpdatedBy = "System",
                            UserId = 1,
                            VenueId = 2
                        });
                });

            modelBuilder.Entity("EventRegistrationApplication.Domain.EventRegistrationApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c7d7a4c0-31dd-48dc-be92-08ccd38abf43",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 10, 16, 1, 47, 119, DateTimeKind.Local).AddTicks(8221),
                            DateUpdated = new DateTime(2025, 2, 10, 16, 1, 47, 119, DateTimeKind.Local).AddTicks(8240),
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMFa9GSIBS9M7I32sbdkTeEfhzVZlH2+kiA3DNYP0tCTzVFdbIU+v0WOpoAXNYup4Q==",
                            PhoneNumber = "123-456-7890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c8900b59-6274-467e-b6b2-0809c371fb27",
                            TwoFactorEnabled = false,
                            UpdatedBy = "System",
                            UserName = "admin@localhost.com"
                        });
                });

            modelBuilder.Entity("EventRegistrationApplication.Domain.Registration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SeatsReserved")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RegistrationId");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("Registration");

                    b.HasData(
                        new
                        {
                            RegistrationId = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9791),
                            DateUpdated = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9792),
                            EventId = 1,
                            RegistrationDate = new DateTime(2025, 2, 10, 16, 1, 47, 58, DateTimeKind.Local).AddTicks(9787),
                            SeatsReserved = 2,
                            UpdatedBy = "System",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("EventRegistrationApplication.Domain.SeatSelection", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("GridCoordinates")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("SeatPrice")
                        .HasColumnType("int");

                    b.Property<int>("SeatStatusId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SeatId");

                    b.HasIndex("EventId");

                    b.HasIndex("SeatStatusId");

                    b.ToTable("seatSelections");

                    b.HasData(
                        new
                        {
                            SeatId = 1,
                            CreatedBy = "",
                            DateCreated = new DateTime(2025, 2, 10, 8, 1, 47, 119, DateTimeKind.Utc).AddTicks(9691),
                            DateUpdated = new DateTime(2025, 2, 10, 8, 1, 47, 119, DateTimeKind.Utc).AddTicks(9691),
                            EventId = 1,
                            GridCoordinates = "A1",
                            SeatPrice = 100,
                            SeatStatusId = 1,
                            UpdatedBy = "",
                            UserId = 0
                        },
                        new
                        {
                            SeatId = 2,
                            CreatedBy = "",
                            DateCreated = new DateTime(2025, 2, 10, 8, 1, 47, 119, DateTimeKind.Utc).AddTicks(9696),
                            DateUpdated = new DateTime(2025, 2, 10, 8, 1, 47, 119, DateTimeKind.Utc).AddTicks(9697),
                            EventId = 1,
                            GridCoordinates = "A2",
                            SeatPrice = 150,
                            SeatStatusId = 2,
                            UpdatedBy = "",
                            UserId = 0
                        },
                        new
                        {
                            SeatId = 3,
                            CreatedBy = "",
                            DateCreated = new DateTime(2025, 2, 10, 8, 1, 47, 119, DateTimeKind.Utc).AddTicks(9698),
                            DateUpdated = new DateTime(2025, 2, 10, 8, 1, 47, 119, DateTimeKind.Utc).AddTicks(9699),
                            EventId = 1,
                            GridCoordinates = "B1",
                            SeatPrice = 200,
                            SeatStatusId = 1,
                            UpdatedBy = "",
                            UserId = 0
                        },
                        new
                        {
                            SeatId = 4,
                            CreatedBy = "",
                            DateCreated = new DateTime(2025, 2, 10, 8, 1, 47, 119, DateTimeKind.Utc).AddTicks(9700),
                            DateUpdated = new DateTime(2025, 2, 10, 8, 1, 47, 119, DateTimeKind.Utc).AddTicks(9700),
                            EventId = 1,
                            GridCoordinates = "B2",
                            SeatPrice = 250,
                            SeatStatusId = 1,
                            UpdatedBy = "",
                            UserId = 0
                        },
                        new
                        {
                            SeatId = 5,
                            CreatedBy = "",
                            DateCreated = new DateTime(2025, 2, 10, 8, 1, 47, 119, DateTimeKind.Utc).AddTicks(9702),
                            DateUpdated = new DateTime(2025, 2, 10, 8, 1, 47, 119, DateTimeKind.Utc).AddTicks(9702),
                            EventId = 2,
                            GridCoordinates = "C1",
                            SeatPrice = 120,
                            SeatStatusId = 3,
                            UpdatedBy = "",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("EventRegistrationApplication.Domain.SeatStatusModel", b =>
                {
                    b.Property<int>("SeatStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatStatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SeatStatusId");

                    b.ToTable("SeatStatuses");

                    b.HasData(
                        new
                        {
                            SeatStatusId = 1,
                            StatusName = "Available"
                        },
                        new
                        {
                            SeatStatusId = 2,
                            StatusName = "Reserved"
                        },
                        new
                        {
                            SeatStatusId = 3,
                            StatusName = "Occupied"
                        });
                });

            modelBuilder.Entity("EventRegistrationApplication.Domain.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 10, 16, 1, 47, 59, DateTimeKind.Local).AddTicks(272),
                            DateUpdated = new DateTime(2025, 2, 10, 16, 1, 47, 59, DateTimeKind.Local).AddTicks(272),
                            StatusName = "Active",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            StatusId = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 10, 16, 1, 47, 59, DateTimeKind.Local).AddTicks(276),
                            DateUpdated = new DateTime(2025, 2, 10, 16, 1, 47, 59, DateTimeKind.Local).AddTicks(276),
                            StatusName = "Inactive",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("EventRegistrationApplication.Domain.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicPreferences")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("EventRegistrationApplication.Domain.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenueId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VenueId");

                    b.ToTable("Venue");

                    b.HasData(
                        new
                        {
                            VenueId = 1,
                            Capacity = 55000,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 10, 16, 1, 47, 119, DateTimeKind.Local).AddTicks(9204),
                            DateUpdated = new DateTime(2025, 2, 10, 16, 1, 47, 119, DateTimeKind.Local).AddTicks(9205),
                            Location = "Singapore",
                            UpdatedBy = "System",
                            VenueName = "National Stadium"
                        },
                        new
                        {
                            VenueId = 2,
                            Capacity = 12000,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 10, 16, 1, 47, 119, DateTimeKind.Local).AddTicks(9210),
                            DateUpdated = new DateTime(2025, 2, 10, 16, 1, 47, 119, DateTimeKind.Local).AddTicks(9211),
                            Location = "Singapore",
                            UpdatedBy = "System",
                            VenueName = "Singapore Indoor Stadium"
                        },
                        new
                        {
                            VenueId = 3,
                            Capacity = 922,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 10, 16, 1, 47, 119, DateTimeKind.Local).AddTicks(9213),
                            DateUpdated = new DateTime(2025, 2, 10, 16, 1, 47, 119, DateTimeKind.Local).AddTicks(9214),
                            Location = "Singapore",
                            UpdatedBy = "System",
                            VenueName = "Gateway Theatre (Main Theatre)"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ad2bcf0c-20db-474f-8407-5a6b159518ba",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "bd2bcf0c-20db-474f-8407-5a6b159518bb",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            RoleId = "ad2bcf0c-20db-474f-8407-5a6b159518ba"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EventRegistrationApplication.Domain.Registration", b =>
                {
                    b.HasOne("EventRegistrationApplication.Domain.EventModel", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventRegistrationApplication.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventRegistrationApplication.Domain.SeatSelection", b =>
                {
                    b.HasOne("EventRegistrationApplication.Domain.EventModel", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventRegistrationApplication.Domain.SeatStatusModel", "SeatStatus")
                        .WithMany()
                        .HasForeignKey("SeatStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("SeatStatus");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EventRegistrationApplication.Domain.EventRegistrationApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EventRegistrationApplication.Domain.EventRegistrationApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventRegistrationApplication.Domain.EventRegistrationApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EventRegistrationApplication.Domain.EventRegistrationApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
